export const CODE_TEMPLATES = {
  passthrough: {label:'Teruskan data',javascript:'return $input.all();',python:'return _input.all()'},
  filter: {label:'Filter status aktif',javascript:"return $input.all().filter(item => item.json.status === 'active');",python:"return [item for item in _input.all() if item['json'].get('status') == 'active']"},
  map: {label:'Pilih & ubah kolom',javascript:"return $input.all().map(item => ({json: {id: item.json.id, total: Number(item.json.amount || 0) * 1.11}}));",python:"return [{'json': {'id': item['json'].get('id'), 'total': float(item['json'].get('amount', 0)) * 1.11}} for item in _input.all()]"},
  dedup: {label:'Buang duplikat ID',javascript:"const seen = new Set();\nreturn $input.all().filter(item => {\n  const key = String(item.json.id);\n  if (seen.has(key)) return false;\n  seen.add(key);\n  return true;\n});",python:"seen = set()\noutput = []\nfor item in _input.all():\n    key = str(item['json'].get('id'))\n    if key not in seen:\n        seen.add(key)\n        output.append(item)\nreturn output"},
  split: {label:'Pecah array menjadi item',javascript:"const data = $input.first()?.json.items || [];\nreturn data.map(value => ({json: value}));",python:"data = _input.first()['json'].get('items', [])\nreturn [{'json': value} for value in data]"},
  aggregate: {label:'Hitung jumlah & total',javascript:"const data = $input.all();\nreturn [{json: {count: data.length, total: data.reduce((sum, item) => sum + Number(item.json.amount || 0), 0)}}];",python:"data = _input.all()\nreturn [{'json': {'count': len(data), 'total': sum(float(item['json'].get('amount', 0)) for item in data)}}]"},
  chats: {label:'Saring chat pribadi',javascript:"const data = $input.first()?.json || {};\nconst chats = Object.fromEntries(Object.entries(data.chats || {}).filter(([id, chat]) => !chat.is_group && !id.endsWith('@g.us') && (chat.messages || []).length > 0));\nreturn [{json: {...data, chats, contacts: Object.keys(chats).length}}];",python:"data = _input.first()['json']\nchats = {key: chat for key, chat in data.get('chats', {}).items() if not chat.get('is_group') and not key.endswith('@g.us') and chat.get('messages')}\nreturn [{'json': {**data, 'chats': chats, 'contacts': len(chats)}}]"},
} as const;
export const CODE_SAMPLE = JSON.stringify([{id:1,status:'active',amount:100},{id:2,status:'inactive',amount:200},{id:1,status:'active',amount:50}],null,2);
